apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector-container
        image: quay.io/testnetworkfunction/collector:latest
        env:
          - name: DB_CONN_STR
            value: "collectoruser:password@tcp(mysql.default.svc.cluster.local:3306)/"
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: Always